-- Supabase database structure for Halima Sadia Madrasa
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  roll text not null,
  name text not null,
  class_name text,
  section text,
  guardian_name text,
  created_at timestamptz default now()
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  name text not null,
  exam_year integer not null,
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  full_mark numeric default 100
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  exam_id bigint references public.exams(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete cascade,
  marks numeric not null,
  grade text,
  created_at timestamptz default now(),
  unique(student_id, exam_id, subject_id)
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  published boolean default false,
  created_at timestamptz default now()
);

alter table public.students enable row level security;
alter table public.exams enable row level security;
alter table public.subjects enable row level security;
alter table public.results enable row level security;
alter table public.notices enable row level security;
